/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokominuman;

import java.awt.print.PrinterException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author theus
 */
public class Order extends javax.swing.JFrame {

    public Order() {
       initComponents();
       jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
       jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
    }

    @SuppressWarnings("empty-statement")
    public void addtable1(int id, String name, int qty, double price) {
       
     DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
      DecimalFormat df = new DecimalFormat("00.00");
      double totPrice = price * Double.valueOf(qty);
      String TotalPrice = df.format(totPrice);
     
     for (int row = 0; row < jTable1.getRowCount(); row++){
         if (name == jTable1.getValueAt(row, 1) ){
             dt.removeRow(jTable1.convertColumnIndexToModel(row));
         }
     }
     
     
     Vector v = new Vector();
     
     v.add(id);
     v.add(name);
     v.add(qty);
     v.add(totPrice);
     
     dt.addRow(v);
    }
public void cal(){

    int numOfRow = jTable1.getRowCount();
    double tot = 0.0;
    
    for (int i = 0; i < numOfRow; i++){
        double value = Double.valueOf(jTable1.getValueAt(i,3).toString());
        tot += value;
    }
    DecimalFormat df = new DecimalFormat("00.00");
    total.setText(df.format(tot));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        q1 = new javax.swing.JLabel();
        Americano = new javax.swing.JButton();
        BlueLagoon = new javax.swing.JButton();
        q2 = new javax.swing.JLabel();
        Cappucino = new javax.swing.JButton();
        q3 = new javax.swing.JLabel();
        Chocolate = new javax.swing.JButton();
        q4 = new javax.swing.JLabel();
        Espresso = new javax.swing.JButton();
        q5 = new javax.swing.JLabel();
        Matcha = new javax.swing.JButton();
        q6 = new javax.swing.JLabel();
        Orange = new javax.swing.JButton();
        q7 = new javax.swing.JLabel();
        Tea = new javax.swing.JButton();
        q8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1145, 745));
        setPreferredSize(new java.awt.Dimension(1145, 745));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 450));
        jPanel1.setLayout(null);

        q1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q1.setText("0");
        jPanel1.add(q1);
        q1.setBounds(0, 176, 154, 47);

        Americano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minuman List/Americano.jpg"))); // NOI18N
        Americano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanoActionPerformed(evt);
            }
        });
        jPanel1.add(Americano);
        Americano.setBounds(0, 0, 154, 170);

        BlueLagoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minuman List/Blue Lagoon Mocktail.jpg"))); // NOI18N
        BlueLagoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueLagoonActionPerformed(evt);
            }
        });
        jPanel1.add(BlueLagoon);
        BlueLagoon.setBounds(190, 0, 154, 170);

        q2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q2.setText("0");
        jPanel1.add(q2);
        q2.setBounds(190, 180, 154, 47);

        Cappucino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minuman List/Capuccino.jpg"))); // NOI18N
        Cappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CappucinoActionPerformed(evt);
            }
        });
        jPanel1.add(Cappucino);
        Cappucino.setBounds(380, 0, 154, 170);

        q3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q3.setText("0");
        jPanel1.add(q3);
        q3.setBounds(380, 180, 154, 47);

        Chocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minuman List/Chocolate Milkshake.jpg"))); // NOI18N
        Chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocolateActionPerformed(evt);
            }
        });
        jPanel1.add(Chocolate);
        Chocolate.setBounds(0, 230, 154, 170);

        q4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        q4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q4.setText("0");
        jPanel1.add(q4);
        q4.setBounds(0, 410, 154, 47);

        Espresso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minuman List/Espresso.jpg"))); // NOI18N
        Espresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspressoActionPerformed(evt);
            }
        });
        jPanel1.add(Espresso);
        Espresso.setBounds(190, 230, 154, 170);

        q5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        q5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q5.setText("0");
        jPanel1.add(q5);
        q5.setBounds(190, 410, 154, 47);

        Matcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minuman List/Matcha.jpg"))); // NOI18N
        Matcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatchaActionPerformed(evt);
            }
        });
        jPanel1.add(Matcha);
        Matcha.setBounds(380, 230, 154, 170);

        q6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        q6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q6.setText("0");
        jPanel1.add(q6);
        q6.setBounds(380, 410, 154, 47);

        Orange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minuman List/Orange Juice.jpg"))); // NOI18N
        Orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrangeActionPerformed(evt);
            }
        });
        jPanel1.add(Orange);
        Orange.setBounds(0, 470, 154, 170);

        q7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        q7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q7.setText("0");
        jPanel1.add(q7);
        q7.setBounds(0, 650, 154, 47);

        Tea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minuman List/Tea.jpg"))); // NOI18N
        Tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaActionPerformed(evt);
            }
        });
        jPanel1.add(Tea);
        Tea.setBounds(190, 470, 154, 170);

        q8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        q8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q8.setText("0");
        jPanel1.add(q8);
        q8.setBounds(190, 650, 154, 47);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        b.setColumns(20);
        b.setRows(5);
        jScrollPane2.setViewportView(b);

        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Total:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 99, 50);

        total.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(total);
        total.setBounds(117, 6, 99, 50);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(450, 10, 120, 150);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(240, 0, 72, 23);

        jLabel3.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Toko Minuman");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 230, 580, 60);

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("'Sugar Rush'");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 290, 580, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanoActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q1.getText());
        ++i;
        q1.setText(String.valueOf(i));
        addtable1(1, "Americano", i, 1.99);
        
        cal();
    }//GEN-LAST:event_AmericanoActionPerformed

    private void BlueLagoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueLagoonActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q2.getText());
        ++i;
        q2.setText(String.valueOf(i));
        addtable1(2, "Blue Lagoon", i, 2.99);
        
        cal();
    }//GEN-LAST:event_BlueLagoonActionPerformed

    private void CappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CappucinoActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q3.getText());
        ++i;
        q3.setText(String.valueOf(i));
        addtable1(3, "Cappucino", i, 2.55);
        
        cal();
    }//GEN-LAST:event_CappucinoActionPerformed

    private void ChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocolateActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q4.getText());
        ++i;
        q4.setText(String.valueOf(i));
        addtable1(4, "Chocolate M.", i, 3.29);
        
        cal();
    }//GEN-LAST:event_ChocolateActionPerformed

    private void EspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspressoActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q5.getText());
        ++i;
        q5.setText(String.valueOf(i));
        addtable1(5, "Espresso", i, 1.79);
        
        cal();
    }//GEN-LAST:event_EspressoActionPerformed

    private void MatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatchaActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q6.getText());
        ++i;
        q6.setText(String.valueOf(i));
        addtable1(6, "Americano", i, 2.49);
        
        cal();
    }//GEN-LAST:event_MatchaActionPerformed

    private void OrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrangeActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q7.getText());
        ++i;
        q7.setText(String.valueOf(i));
        addtable1(7, "Orange", i, 2.19);
        
        cal();
    }//GEN-LAST:event_OrangeActionPerformed

    private void TeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(q8.getText());
        ++i;
        q8.setText(String.valueOf(i));
        addtable1(8, "Tea", i, 1.79);
        
        cal();
    }//GEN-LAST:event_TeaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        String r = dt.getValueAt(jTable1.getSelectedRow(),0).toString();
        int rw = jTable1.getSelectedRow();
        dt.removeRow(rw);
        
        
        System.out.println(r);
        switch(r){
            case "1":
                q1.setText("0");
                break;
            case "2":
                q2.setText("0");
                break;
            case "3":
                q3.setText("0");
                break;
            case "4":
                q4.setText("0");
                break;
            case "5":
                q5.setText("0");
                break;
            case "6":
                q6.setText("0");
                break;
            case "7":
                q7.setText("0");
                break;
            case "8":
                q8.setText("0");
                break;
                
            default:
                System.out.println("Over");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            b.setText("          Dapp code IDN \n");
            b.setText(b.getText()+"         Jls. Serang\n");
            b.setText(b.getText()+"         Banten, Indonesia\n");
            b.setText(b.getText()+"         +62 81928312312\n");
            b.setText(b.getText()+"_________________________________________\n");
            b.setText(b.getText()+"  Item \tQty \tPrice"+ "\n");
            b.setText(b.getText()+"_________________________________________\n");
            
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            
            for(int i=0; i < jTable1.getRowCount();i++){
                String name = dt.getValueAt(i, 1).toString();
                String qty = dt.getValueAt(i, 2).toString();
                String price = dt.getValueAt(i, 3).toString();
                
                b.setText(b.getText() +"  " +name +"\t\t" +qty +"\t" +price +"\n");
            }
            
            b.setText(b.getText()+"_________________________________________\n");
            b.setText(b.getText()+"Subtotal: " +total.getText() + "\n");
            b.setText(b.getText()+"_________________________________________\n");
            b.setText(b.getText()+"             Terima kasih atas kunjungannya!" + "\n");
            b.setText(b.getText()+"_________________________________________\n");
            
            b.print();
        
        }
        catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Americano;
    private javax.swing.JButton BlueLagoon;
    private javax.swing.JButton Cappucino;
    private javax.swing.JButton Chocolate;
    private javax.swing.JButton Espresso;
    private javax.swing.JButton Matcha;
    private javax.swing.JButton Orange;
    private javax.swing.JButton Tea;
    private javax.swing.JTextArea b;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q6;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel q8;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables


    private void addtable(int i, String aMericano, int i0, double d) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
